spring:
  application:
    name: checkout
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true