spring:
  application:
    name: stock
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/stockdb
    username: postgres
    password: postgres
    pool:
      initial-size: 3
      min-idle: 3
      max-size: 3
      max-idle-time: 30m
      max-life-time: 30m
      validation-query: SELECT 1

aws:
  s3:
    bucket: product-images-bucket
    region: us-east-1
    endpoint: http://localhost:4566
    secret-access-key: test
    access-key-id: test
    endpoint-override:
      enabled: true
      url: http://localhost:4566
      region: us-east-1
    netty-nio-properties:
      write-timeout: 0
      max-concurrency: 1000
      max-pending-connections-acquires: 10000
      connect-timeout: 30
      connection-acquisition-timeout: 10s