apiVersion: 1
datasources:
  - name: Prometheus
    uid: DS_PROMETHEUS
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1
